### ISSUE TITLE
Request: Ability to use testing data for performance evaluation

### ISSUE THREAD

**Issue by patrickheindel** [ModelOriented/survex#76]
Hi all - really appreciate your excellent work on this much needed package thus far. I am writing to inquire about a potential feature request. 

In model_performance() and its helper functions (e.g., surv_model_performance), the "newdata" argument is extracted from the trained model object. It would be very useful to be able to specify an alternative (presumably randomly split) dataframe to be used for performance evaluation (_i.e._, provide a "test" dataset). Perhaps this "test_data" dataframe could be specified at the explain() step, and then preferentially extracted for use in model_performance().

A separate option (but potentially more complex to implement) would be to build in k-fold cross validation.

Please let me know if I am fundamentally misunderstanding something about your package. Forgive me if this isn't the best place to raise this issue, I'm a github noob. Thanks again for all the great work.

**Comment by mikolajsp** [comment]
Hi, sorry for the long wait to get to this issue.

It is possible to use different subsets for training and assessing performance (as well as explainations), but according to the design of the package it is done via the explainer objects. 

You can manually provide the data when creating the explainer so that it is not extracted automatically from the model. 

Here is a basic example to demonstrate this behavior:

```r
library(survex)
library(survival)

set.seed(123)
train <- sample(1:nrow(veteran), 100)

train_veteran <- veteran[train, ]
test_veteran <- veteran[-train, ]

cox_model <- coxph(Surv(time, status) ~., data = train_veteran, x = T, y = T)

train_explainer <- explain(cox_model, data = train_veteran, y = Surv(train_veteran$time, train_veteran$status), label = "train")
test_explainer <- explain(cox_model, data = test_veteran, y = Surv(test_veteran$time, test_veteran$status), label = "test")

train_performance <- model_performance(train_explainer)
test_performance <- model_performance(test_explainer)

plot(train_performance, test_performance)
```
![model_performance](https://github.com/ModelOriented/survex/assets/55801784/5666ef05-ca07-42d1-87e9-cd7b9a864247)

Hope this helps in your case. I'm closing the issue, but if you have any further questions feel free to reopen.
